# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'disease_classifier.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(511, 764)
        self.gridLayout_4 = QtWidgets.QGridLayout(Form)
        self.gridLayout_4.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_aid = QtWidgets.QWidget()
        self.tab_aid.setObjectName("tab_aid")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab_aid)
        self.gridLayout_9.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.btn_aid_add_rtdc = QtWidgets.QPushButton(self.tab_aid)
        self.btn_aid_add_rtdc.setCheckable(False)
        self.btn_aid_add_rtdc.setChecked(False)
        self.btn_aid_add_rtdc.setObjectName("btn_aid_add_rtdc")
        self.gridLayout_9.addWidget(self.btn_aid_add_rtdc, 2, 0, 1, 1)
        self.splitter_2 = QtWidgets.QSplitter(self.tab_aid)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setChildrenCollapsible(False)
        self.splitter_2.setObjectName("splitter_2")
        self.groupBox_aid_files = QtWidgets.QGroupBox(self.splitter_2)
        self.groupBox_aid_files.setEnabled(True)
        self.groupBox_aid_files.setObjectName("groupBox_aid_files")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_aid_files)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.table_aid_files = MyTable(self.groupBox_aid_files)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_aid_files.sizePolicy().hasHeightForWidth())
        self.table_aid_files.setSizePolicy(sizePolicy)
        self.table_aid_files.setObjectName("table_aid_files")
        self.table_aid_files.setColumnCount(4)
        self.table_aid_files.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_aid_files.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_aid_files.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_aid_files.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_aid_files.setHorizontalHeaderItem(3, item)
        self.table_aid_files.horizontalHeader().setSortIndicatorShown(False)
        self.table_aid_files.horizontalHeader().setStretchLastSection(False)
        self.gridLayout_8.addWidget(self.table_aid_files, 0, 0, 1, 2)
        self.btn_aid_classify = QtWidgets.QPushButton(self.groupBox_aid_files)
        self.btn_aid_classify.setCheckable(False)
        self.btn_aid_classify.setChecked(False)
        self.btn_aid_classify.setObjectName("btn_aid_classify")
        self.gridLayout_8.addWidget(self.btn_aid_classify, 2, 0, 1, 2)
        self.splitter = QtWidgets.QSplitter(self.groupBox_aid_files)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName("splitter")
        self.btn_aid_load_model = QtWidgets.QPushButton(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_aid_load_model.sizePolicy().hasHeightForWidth())
        self.btn_aid_load_model.setSizePolicy(sizePolicy)
        self.btn_aid_load_model.setMaximumSize(QtCore.QSize(100, 16777215))
        self.btn_aid_load_model.setObjectName("btn_aid_load_model")
        self.lineEdit_aid_model_path = MyLineEdit(self.splitter)
        self.lineEdit_aid_model_path.setEnabled(False)
        self.lineEdit_aid_model_path.setDragEnabled(True)
        self.lineEdit_aid_model_path.setObjectName("lineEdit_aid_model_path")
        self.gridLayout_8.addWidget(self.splitter, 1, 0, 1, 2)
        self.groupBox_aid_analy = QtWidgets.QGroupBox(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_aid_analy.sizePolicy().hasHeightForWidth())
        self.groupBox_aid_analy.setSizePolicy(sizePolicy)
        self.groupBox_aid_analy.setObjectName("groupBox_aid_analy")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.groupBox_aid_analy)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.table_aid_analy = MyTable(self.groupBox_aid_analy)
        self.table_aid_analy.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_aid_analy.sizePolicy().hasHeightForWidth())
        self.table_aid_analy.setSizePolicy(sizePolicy)
        self.table_aid_analy.setObjectName("table_aid_analy")
        self.table_aid_analy.setColumnCount(5)
        self.table_aid_analy.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_aid_analy.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_aid_analy.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_aid_analy.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_aid_analy.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_aid_analy.setHorizontalHeaderItem(4, item)
        self.table_aid_analy.horizontalHeader().setMinimumSectionSize(45)
        self.gridLayout_25.addWidget(self.table_aid_analy, 1, 0, 1, 1)
        self.label_phenotype = QtWidgets.QLabel(self.groupBox_aid_analy)
        self.label_phenotype.setText("")
        self.label_phenotype.setObjectName("label_phenotype")
        self.gridLayout_25.addWidget(self.label_phenotype, 0, 0, 1, 1)
        self.groupBox_dise_class = QtWidgets.QGroupBox(self.splitter_2)
        self.groupBox_dise_class.setObjectName("groupBox_dise_class")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_dise_class)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.table_dise_class = MyTable(self.groupBox_dise_class)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_dise_class.sizePolicy().hasHeightForWidth())
        self.table_dise_class.setSizePolicy(sizePolicy)
        self.table_dise_class.setObjectName("table_dise_class")
        self.table_dise_class.setColumnCount(2)
        self.table_dise_class.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_dise_class.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dise_class.setHorizontalHeaderItem(1, item)
        self.table_dise_class.horizontalHeader().setStretchLastSection(False)
        self.gridLayout_10.addWidget(self.table_dise_class, 1, 0, 1, 1)
        self.label_disease = QtWidgets.QLabel(self.groupBox_dise_class)
        self.label_disease.setText("")
        self.label_disease.setObjectName("label_disease")
        self.gridLayout_10.addWidget(self.label_disease, 0, 0, 1, 1)
        self.gridLayout_9.addWidget(self.splitter_2, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_aid, "")
        self.gridLayout_4.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_aid_add_rtdc.setText(_translate("Form", "Add classification to .rtdc file"))
        self.groupBox_aid_files.setToolTip(_translate("Form", "Drag and drop .rtdc files here."))
        self.groupBox_aid_files.setTitle(_translate("Form", "Files table"))
        self.table_aid_files.setToolTip(_translate("Form", "Drag and drop .rtdc or .bin files here."))
        item = self.table_aid_files.horizontalHeaderItem(0)
        item.setText(_translate("Form", "TF"))
        item = self.table_aid_files.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Load"))
        item = self.table_aid_files.horizontalHeaderItem(2)
        item.setText(_translate("Form", "File Path"))
        item = self.table_aid_files.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Del"))
        self.btn_aid_classify.setText(_translate("Form", "Classify"))
        self.btn_aid_load_model.setText(_translate("Form", "Load model"))
        self.lineEdit_aid_model_path.setToolTip(_translate("Form", "Drag and drop the model folder containing the .pb file and meta.xlsx file here."))
        self.groupBox_aid_analy.setTitle(_translate("Form", "Phenotype classification"))
        item = self.table_aid_analy.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Load"))
        item = self.table_aid_analy.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Class"))
        item = self.table_aid_analy.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Name"))
        item = self.table_aid_analy.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Nr. of events"))
        item = self.table_aid_analy.horizontalHeaderItem(4)
        item.setText(_translate("Form", "% of events"))
        self.groupBox_dise_class.setTitle(_translate("Form", "Disease classification"))
        item = self.table_dise_class.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Disease"))
        item = self.table_dise_class.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Probability"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_aid), _translate("Form", "Disease classif."))
from CustomWidget import MyLineEdit, MyTable
import art_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
